name: vanilla_counter
maintainer: Bilal Uslu (@bilaluslu)
description: Redux Saga Vanilla Counter Example
version: 1.0.0
homepage: https://github.com/reduxsaga/vanilla_counter
repository: https://github.com/reduxsaga/vanilla_counter

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  redux: ^4.0.0
  redux_saga: ^1.1.0

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
